# -*- coding: utf-8 -*-
"""Exercicio_Mod1_Calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wf9Ao9xO8CS9BVuga3JawL8I2CFaU2Y8
"""

#Calculadora

while True:

  print('Escolha a operação desejada: \n')
  print("1 - Adição")
  print("2 - Subtração")
  print("3 - Multiplicação")
  print("4 - Divisão")
  print("5 - Sair \n")

  operacao = input("Selecione a operação: ")

  if operacao == '5':
    print("Saindo da calculadora, volte sempre!")
    break

  if operacao not in ['1', '2', '3', '4']:
      print("Opção inválida! Tente novamente. \n")
      continue

  try:
      num1 = float(input("Digite o primeiro número: "))
      num2 = float(input("Digite o segundo número: "))
  except ValueError:
      print("Entrada inválida. Certifique-se de usar dados válidos. \n")
      continue
  if operacao == '1':
      resultado = num1 + num2
      print(f"Resultado: {num1} + {num2} = {resultado}")
  elif operacao == '2':
      resultado = num1 - num2
      print(f"Resultado: {num1} - {num2} = {resultado}")
  elif operacao == '3':
      resultado = num1 * num2
      print(f"Resultado: {num1} * {num2} = {resultado}")
  elif operacao == '4':
      if num2 == 0:
          print("Erro: Divisão por zero não é válida.")
      else:
          resultado = num1 / num2
          print(f"Resultado: {num1} / {num2} = {resultado}")